server:
  port: 8081

spring:
  application:
    name: producer-service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    properties:
      schema.registry.url: ${SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL:http://localhost:8081}
    topic:
      orders: orders

logging:
  level:
    org.apache.kafka: INFO
    com.kafka.producer: DEBUG
